(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)
(*                                                                             *)
(*         This file has been automatically generated by FeynRules.            *)
(*                                                                             *)
(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)


FR$ModelInformation={
  ModelName->"Zee Model",
  Authors -> {"Yang Ma"},
  Version -> "1.0.0",
  Date -> "04. 09. 2019",
  Institutions -> {"University of Pittsburgh"},
  Emails -> {"mayangluon@pitt.edu"}};

FR$ClassesTranslation={A -> V[1], Z -> V[2], W -> V[3], G -> V[4], ghA -> U[1], ghZ -> U[2], ghWp -> U[3], ghWm -> U[4], ghG -> U[5], ve -> F[1], vm -> F[2], vt -> F[3], e -> F[4], mu -> F[5], ta -> F[6], u -> F[7], c -> F[8], t -> F[9], d -> F[10], s -> F[11], b -> F[12], HL -> S[1], HH -> S[2], HA -> S[3], HpH -> S[4], Hp -> S[5], G0 -> S[6], GP -> S[7]};

FR$InteractionOrderPerturbativeExpansion={{QCD, 0}, {QED, 0}, {ZEE, 0}};

FR$GoldstoneList={S[6], S[7]};

(*     Declared indices    *)

IndexRange[ Index[Gluon] ] = NoUnfold[ Range[ 8 ] ]

IndexRange[ Index[SU2W] ] = Range[ 3 ]

IndexRange[ Index[Generation] ] = Range[ 3 ]

IndexRange[ Index[Colour] ] = NoUnfold[ Range[ 3 ] ]

IndexRange[ Index[SU2D] ] = Range[ 2 ]

(*     Declared particles    *)

M$ClassesDescription = {
V[1] == {
    SelfConjugate -> True,
    PropagatorType -> Sine,
    PropagatorArrow -> None,
    Mass -> 0,
    Indices -> {},
    PropagatorLabel -> "A" },

V[2] == {
    SelfConjugate -> True,
    PropagatorType -> Sine,
    PropagatorArrow -> None,
    Mass -> MZ,
    Indices -> {},
    PropagatorLabel -> "Z" },

V[3] == {
    SelfConjugate -> False,
    QuantumNumbers -> {Q},
    PropagatorType -> Sine,
    PropagatorArrow -> Forward,
    Mass -> MW,
    Indices -> {},
    PropagatorLabel -> "W" },

V[4] == {
    SelfConjugate -> True,
    PropagatorType -> Cycles,
    PropagatorArrow -> None,
    Mass -> 0,
    Indices -> {Index[Gluon]},
    PropagatorLabel -> "G" },

U[1] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber},
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> 0,
    Indices -> {},
    PropagatorLabel -> "ghA" },

U[2] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber},
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> MZ,
    Indices -> {},
    PropagatorLabel -> "ghZ" },

U[3] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber, Q},
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> MW,
    Indices -> {},
    PropagatorLabel -> "ghWp" },

U[4] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber, -Q},
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> MW,
    Indices -> {},
    PropagatorLabel -> "ghWm" },

U[5] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber},
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> 0,
    Indices -> {Index[Gluon]},
    PropagatorLabel -> "ghG" },

F[1] == {
    SelfConjugate -> False,
    QuantumNumbers -> {LeptonNumber},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> 0,
    Indices -> {},
    PropagatorLabel -> "ve" },

F[2] == {
    SelfConjugate -> False,
    QuantumNumbers -> {LeptonNumber},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> 0,
    Indices -> {},
    PropagatorLabel -> "vm" },

F[3] == {
    SelfConjugate -> False,
    QuantumNumbers -> {LeptonNumber},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> 0,
    Indices -> {},
    PropagatorLabel -> "vt" },

F[4] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-Q, LeptonNumber},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> Me,
    Indices -> {},
    PropagatorLabel -> "e" },

F[5] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-Q, LeptonNumber},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> MMU,
    Indices -> {},
    PropagatorLabel -> "mu" },

F[6] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-Q, LeptonNumber},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> MTA,
    Indices -> {},
    PropagatorLabel -> "ta" },

F[7] == {
    SelfConjugate -> False,
    QuantumNumbers -> {(2*Q)/3},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> MU,
    Indices -> {Index[Colour]},
    PropagatorLabel -> "u" },

F[8] == {
    SelfConjugate -> False,
    QuantumNumbers -> {(2*Q)/3},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> MC,
    Indices -> {Index[Colour]},
    PropagatorLabel -> "c" },

F[9] == {
    SelfConjugate -> False,
    QuantumNumbers -> {(2*Q)/3},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> MT,
    Indices -> {Index[Colour]},
    PropagatorLabel -> "t" },

F[10] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-Q/3},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> MD,
    Indices -> {Index[Colour]},
    PropagatorLabel -> "d" },

F[11] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-Q/3},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> MS,
    Indices -> {Index[Colour]},
    PropagatorLabel -> "s" },

F[12] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-Q/3},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> MB,
    Indices -> {Index[Colour]},
    PropagatorLabel -> "b" },

S[1] == {
    SelfConjugate -> True,
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> MHL,
    Indices -> {},
    PropagatorLabel -> "HL" },

S[2] == {
    SelfConjugate -> True,
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> MHH,
    Indices -> {},
    PropagatorLabel -> "HH" },

S[3] == {
    SelfConjugate -> True,
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> MHA,
    Indices -> {},
    PropagatorLabel -> "HA" },

S[4] == {
    SelfConjugate -> False,
    QuantumNumbers -> {Q},
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> MHpH,
    Indices -> {},
    PropagatorLabel -> "HpH" },

S[5] == {
    SelfConjugate -> False,
    QuantumNumbers -> {Q},
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> MHp,
    Indices -> {},
    PropagatorLabel -> "Hp" },

S[6] == {
    SelfConjugate -> True,
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> MZ,
    Indices -> {},
    PropagatorLabel -> "G0" },

S[7] == {
    SelfConjugate -> False,
    QuantumNumbers -> {Q},
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> MW,
    Indices -> {},
    PropagatorLabel -> "GP" }
}


(*        Definitions       *)

GaugeXi[ V[1] ] = GaugeXi[A];
GaugeXi[ V[2] ] = GaugeXi[Z];
GaugeXi[ V[3] ] = GaugeXi[W];
GaugeXi[ V[4] ] = GaugeXi[G];
GaugeXi[ U[1] ] = GaugeXi[A];
GaugeXi[ U[2] ] = GaugeXi[Z];
GaugeXi[ U[3] ] = GaugeXi[W];
GaugeXi[ U[4] ] = GaugeXi[W];
GaugeXi[ U[5] ] = GaugeXi[G];
GaugeXi[ S[1] ] = 1;
GaugeXi[ S[2] ] = 1;
GaugeXi[ S[3] ] = 1;
GaugeXi[ S[4] ] = 1;
GaugeXi[ S[5] ] = 1;
GaugeXi[ S[6] ] = GaugeXi[Z];
GaugeXi[ S[7] ] = GaugeXi[W];

MZ[ ___ ] := MZ;
MW[ ___ ] := MW;
Me[ ___ ] := Me;
MMU[ ___ ] := MMU;
MTA[ ___ ] := MTA;
MU[ ___ ] := MU;
MC[ ___ ] := MC;
MT[ ___ ] := MT;
MD[ ___ ] := MD;
MS[ ___ ] := MS;
MB[ ___ ] := MB;
MHL[ ___ ] := MHL;
MHH[ ___ ] := MHH;
MHA[ ___ ] := MHA;
MHpH[ ___ ] := MHpH;
MHp[ ___ ] := MHp;


TheLabel[ V[4, {__}] ] := TheLabel[V[4]];
TheLabel[ U[5, {__}] ] := TheLabel[U[5]];
TheLabel[ F[7, {__}] ] := TheLabel[F[7]];
TheLabel[ F[8, {__}] ] := TheLabel[F[8]];
TheLabel[ F[9, {__}] ] := TheLabel[F[9]];
TheLabel[ F[10, {__}] ] := TheLabel[F[10]];
TheLabel[ F[11, {__}] ] := TheLabel[F[11]];
TheLabel[ F[12, {__}] ] := TheLabel[F[12]];


(*      Couplings (calculated by FeynRules)      *)

M$CouplingMatrices = {

C[ V[4, {e1x2}] , V[4, {e2x2}] , V[4, {e3x2}] ] == {{-(gc1*SUNF[e1x2, e2x2, e3x2]), 0}, {gc1*SUNF[e1x2, e2x2, e3x2], 0}, {gc1*SUNF[e1x2, e2x2, e3x2], 0}, {-(gc1*SUNF[e1x2, e2x2, e3x2]), 0}, {-(gc1*SUNF[e1x2, e2x2, e3x2]), 0}, {gc1*SUNF[e1x2, e2x2, e3x2], 0}},

C[ V[4, {e1x2}] , V[4, {e2x2}] , V[4, {e3x2}] , V[4, {e4x2}] ] == {{(-I)*gc2*(SUNF[e1x2, e2x2, e3x2, e4x2] + SUNF[e1x2, e3x2, e2x2, e4x2]), 0}, {I*gc2*(SUNF[e1x2, e2x2, e3x2, e4x2] - SUNF[e1x2, e4x2, e2x2, e3x2]), 0}, {I*gc2*(SUNF[e1x2, e3x2, e2x2, e4x2] + SUNF[e1x2, e4x2, e2x2, e3x2]), 0}},

C[ V[1] , V[3] , -V[3] ] == {{(-I)*gc3, 0}, {I*gc3, 0}, {I*gc3, 0}, {(-I)*gc3, 0}, {(-I)*gc3, 0}, {I*gc3, 0}},

C[ V[1] , V[1] , V[3] , -V[3] ] == {{(-I)*gc4, 0}, {(-I)*gc4, 0}, {(2*I)*gc4, 0}},

C[ V[3] , -V[3] , V[2] ] == {{(-I)*gc5, 0}, {I*gc5, 0}, {I*gc5, 0}, {(-I)*gc5, 0}, {(-I)*gc5, 0}, {I*gc5, 0}},

C[ V[3] , V[3] , -V[3] , -V[3] ] == {{(-I)*gc6, 0}, {(-I)*gc6, 0}, {(2*I)*gc6, 0}},

C[ V[1] , V[3] , -V[3] , V[2] ] == {{(-2*I)*gc7, 0}, {I*gc7, 0}, {I*gc7, 0}},

C[ V[3] , -V[3] , V[2] , V[2] ] == {{(-I)*gc8, 0}, {(-I)*gc8, 0}, {(2*I)*gc8, 0}},

C[ S[6] , S[6] , S[6] , S[6] ] == {{(-3*I)*lam1, 0}},

C[ S[6] , S[6] , S[7] , -S[7] ] == {{(-I)*lam1, 0}},

C[ S[7] , S[7] , -S[7] , -S[7] ] == {{(-2*I)*lam1, 0}},

C[ S[6] , S[6] , S[1] , S[1] ] == {{(-I)*(cab^2*lam1 + 2*cab*lam6*sab + (lam3 + lam4 - lam5)*sab^2), 0}},

C[ S[7] , -S[7] , S[1] , S[1] ] == {{(-I)*(cab^2*lam1 + 2*cab*lam6*sab + lam3*sab^2), 0}},

C[ S[1] , S[1] , S[1] , S[1] ] == {{(-3*I)*(cab^4*lam1 + 4*cab^3*lam6*sab + 2*cab^2*(lam3 + lam4 + lam5)*sab^2 + 4*cab*lam7*sab^3 + lam2*sab^4), 0}},

C[ S[6] , S[3] , S[5] , -S[5] ] == {{(-I)*(cphi^2*lam10 + lam7*sphi^2), 0}},

C[ S[2] , S[1] , S[5] , -S[5] ] == {{(-I)*(cab*sab*(cphi^2*(-lam8 + lam9) + (lam2 - lam3)*sphi^2) + cab^2*(cphi^2*lam10 + lam7*sphi^2) - sab^2*(cphi^2*lam10 + lam7*sphi^2)), 0}},

C[ -S[7] , S[5] , -S[5] , S[4] ] == {{(-I)*cphi*(cphi^2*lam10 - (lam10 - 2*lam7)*sphi^2), 0}},

C[ S[7] , S[5] , -S[5] , -S[4] ] == {{(-I)*cphi*(cphi^2*lam10 - (lam10 - 2*lam7)*sphi^2), 0}},

C[ S[3] , S[3] , S[3] , S[3] ] == {{(-3*I)*lam2, 0}},

C[ S[3] , S[3] , S[2] , S[2] ] == {{(-I)*(cab^2*lam2 - 2*cab*lam7*sab + (lam3 + lam4 - lam5)*sab^2), 0}},

C[ S[2] , S[2] , S[2] , S[2] ] == {{(-3*I)*(cab^4*lam2 - 4*cab^3*lam7*sab + 2*cab^2*(lam3 + lam4 + lam5)*sab^2 - 4*cab*lam6*sab^3 + lam1*sab^4), 0}},

C[ S[3] , S[3] , S[4] , -S[4] ] == {{(-I)*(cphi^2*lam2 + lam9*sphi^2), 0}},

C[ S[2] , S[2] , S[4] , -S[4] ] == {{(-I)*(-2*cab*sab*(cphi^2*lam7 + lam10*sphi^2) + sab^2*(cphi^2*lam3 + lam8*sphi^2) + cab^2*(cphi^2*lam2 + lam9*sphi^2)), 0}},

C[ S[4] , S[4] , -S[4] , -S[4] ] == {{(-2*I)*(cphi^4*lam2 + 2*cphi^2*lam9*sphi^2 + 2*lameta*sphi^4), 0}},

C[ S[6] , S[6] , S[3] , S[3] ] == {{(-I)*(lam3 + lam4 + lam5), 0}},

C[ S[7] , -S[7] , S[3] , S[3] ] == {{(-I)*lam3, 0}},

C[ S[6] , S[6] , S[2] , S[2] ] == {{(-I)*(cab^2*(lam3 + lam4 - lam5) - 2*cab*lam6*sab + lam1*sab^2), 0}},

C[ S[7] , -S[7] , S[2] , S[2] ] == {{(-I)*(cab^2*lam3 - 2*cab*lam6*sab + lam1*sab^2), 0}},

C[ S[3] , S[3] , S[1] , S[1] ] == {{(-I)*(cab^2*(lam3 + lam4 - lam5) + 2*cab*lam7*sab + lam2*sab^2), 0}},

C[ S[2] , S[2] , S[1] , S[1] ] == {{(-I)*(cab^4*(lam3 + lam4 + lam5) + 6*cab^3*(-lam6 + lam7)*sab + cab^2*(3*lam1 + 3*lam2 - 4*(lam3 + lam4 + lam5))*sab^2 + 6*cab*(lam6 - lam7)*sab^3 + (lam3 + lam4 + lam5)*sab^4), 0}},

C[ S[6] , S[6] , S[4] , -S[4] ] == {{(-I)*(cphi^2*lam3 + lam8*sphi^2), 0}},

C[ S[7] , -S[7] , S[4] , -S[4] ] == {{(-I)*(cphi^2*(lam3 + lam4) + lam8*sphi^2), 0}},

C[ S[1] , S[1] , S[4] , -S[4] ] == {{(-I)*(2*cab*sab*(cphi^2*lam7 + lam10*sphi^2) + cab^2*(cphi^2*lam3 + lam8*sphi^2) + sab^2*(cphi^2*lam2 + lam9*sphi^2)), 0}},

C[ S[6] , -S[7] , S[3] , S[4] ] == {{(-I/2)*cphi*(lam4 + lam5), 0}},

C[ S[6] , -S[7] , S[2] , S[4] ] == {{(cab*cphi*(lam4 - lam5))/2, 0}},

C[ -S[7] , S[3] , S[1] , S[4] ] == {{-(cab*cphi*(lam4 - lam5))/2, 0}},

C[ -S[7] , S[2] , S[1] , S[4] ] == {{(-I/2)*cphi*(cab^2*(lam4 + lam5) + 2*cab*(-lam6 + lam7)*sab - (lam4 + lam5)*sab^2), 0}},

C[ S[6] , S[7] , S[3] , -S[4] ] == {{(-I/2)*cphi*(lam4 + lam5), 0}},

C[ S[6] , S[7] , S[2] , -S[4] ] == {{-(cab*cphi*(lam4 - lam5))/2, 0}},

C[ S[7] , S[3] , S[1] , -S[4] ] == {{(cab*cphi*(lam4 - lam5))/2, 0}},

C[ S[7] , S[2] , S[1] , -S[4] ] == {{(-I/2)*cphi*(cab^2*(lam4 + lam5) + 2*cab*(-lam6 + lam7)*sab - (lam4 + lam5)*sab^2), 0}},

C[ S[6] , S[3] , S[2] , S[1] ] == {{(-I)*(cab^2*lam5 + cab*(-lam6 + lam7)*sab - lam5*sab^2), 0}},

C[ -S[7] , -S[7] , S[4] , S[4] ] == {{(-2*I)*cphi^2*lam5, 0}},

C[ S[7] , S[7] , -S[4] , -S[4] ] == {{(-2*I)*cphi^2*lam5, 0}},

C[ S[6] , S[6] , S[6] , S[3] ] == {{(-3*I)*lam6, 0}},

C[ S[6] , S[7] , -S[7] , S[3] ] == {{(-I)*lam6, 0}},

C[ S[6] , S[6] , S[2] , S[1] ] == {{(-I)*(cab^2*lam6 + cab*(-lam1 + lam3 + lam4 - lam5)*sab - lam6*sab^2), 0}},

C[ S[7] , -S[7] , S[2] , S[1] ] == {{(-I)*(cab^2*lam6 + cab*(-lam1 + lam3)*sab - lam6*sab^2), 0}},

C[ S[6] , S[3] , S[1] , S[1] ] == {{(-I)*(cab^2*lam6 + 2*cab*lam5*sab + lam7*sab^2), 0}},

C[ S[2] , S[1] , S[1] , S[1] ] == {{(-3*I)*(cab^4*lam6 + cab^3*(-lam1 + lam3 + lam4 + lam5)*sab + 3*cab^2*(-lam6 + lam7)*sab^2 + cab*(lam2 - lam3 - lam4 - lam5)*sab^3 - lam7*sab^4), 0}},

C[ S[6] , S[6] , -S[7] , S[4] ] == {{(-I)*cphi*lam6, 0}},

C[ S[7] , -S[7] , -S[7] , S[4] ] == {{(-2*I)*cphi*lam6, 0}},

C[ -S[7] , S[1] , S[1] , S[4] ] == {{(-I)*cphi*(cab^2*lam6 + cab*(lam4 + lam5)*sab + lam7*sab^2), 0}},

C[ S[6] , S[6] , S[7] , -S[4] ] == {{(-I)*cphi*lam6, 0}},

C[ S[7] , S[7] , -S[7] , -S[4] ] == {{(-2*I)*cphi*lam6, 0}},

C[ S[7] , S[1] , S[1] , -S[4] ] == {{(-I)*cphi*(cab^2*lam6 + cab*(lam4 + lam5)*sab + lam7*sab^2), 0}},

C[ S[6] , S[3] , S[3] , S[3] ] == {{(-3*I)*lam7, 0}},

C[ S[6] , S[3] , S[2] , S[2] ] == {{(-I)*(cab^2*lam7 - 2*cab*lam5*sab + lam6*sab^2), 0}},

C[ S[3] , S[3] , S[2] , S[1] ] == {{(-I)*(cab^2*lam7 + cab*(lam2 - lam3 - lam4 + lam5)*sab - lam7*sab^2), 0}},

C[ S[2] , S[2] , S[2] , S[1] ] == {{(-3*I)*(cab^4*lam7 + cab^3*(lam2 - lam3 - lam4 - lam5)*sab + 3*cab^2*(lam6 - lam7)*sab^2 + cab*(-lam1 + lam3 + lam4 + lam5)*sab^3 - lam6*sab^4), 0}},

C[ -S[7] , S[3] , S[3] , S[4] ] == {{(-I)*cphi*lam7, 0}},

C[ -S[7] , S[2] , S[2] , S[4] ] == {{(-I)*cphi*(cab^2*lam7 - cab*(lam4 + lam5)*sab + lam6*sab^2), 0}},

C[ S[7] , S[3] , S[3] , -S[4] ] == {{(-I)*cphi*lam7, 0}},

C[ S[7] , S[2] , S[2] , -S[4] ] == {{(-I)*cphi*(cab^2*lam7 - cab*(lam4 + lam5)*sab + lam6*sab^2), 0}},

C[ S[6] , S[3] , S[4] , -S[4] ] == {{(-I)*(cphi^2*lam7 + lam10*sphi^2), 0}},

C[ S[2] , S[1] , S[4] , -S[4] ] == {{(-I)*(cab^2*(cphi^2*lam7 + lam10*sphi^2) - sab^2*(cphi^2*lam7 + lam10*sphi^2) + cab*sab*(cphi^2*(lam2 - lam3) + (-lam8 + lam9)*sphi^2)), 0}},

C[ -S[7] , S[4] , S[4] , -S[4] ] == {{(-2*I)*cphi*(cphi^2*lam7 + lam10*sphi^2), 0}},

C[ S[7] , S[4] , -S[4] , -S[4] ] == {{(-2*I)*cphi*(cphi^2*lam7 + lam10*sphi^2), 0}},

C[ S[6] , S[6] , S[5] , -S[5] ] == {{(-I)*(cphi^2*lam8 + lam3*sphi^2), 0}},

C[ S[7] , -S[7] , S[5] , -S[5] ] == {{(-I)*(cphi^2*lam8 + (lam3 + lam4)*sphi^2), 0}},

C[ S[1] , S[1] , S[5] , -S[5] ] == {{(-I)*(sab^2*(cphi^2*lam9 + lam2*sphi^2) + cab^2*(cphi^2*lam8 + lam3*sphi^2) + 2*cab*sab*(cphi^2*lam10 + lam7*sphi^2)), 0}},

C[ S[3] , S[3] , S[5] , -S[5] ] == {{(-I)*(cphi^2*lam9 + lam2*sphi^2), 0}},

C[ S[2] , S[2] , S[5] , -S[5] ] == {{(-I)*(cab^2*(cphi^2*lam9 + lam2*sphi^2) + sab^2*(cphi^2*lam8 + lam3*sphi^2) - 2*cab*sab*(cphi^2*lam10 + lam7*sphi^2)), 0}},

C[ S[5] , -S[5] , S[4] , -S[4] ] == {{(-I)*(cphi^4*lam9 + 2*cphi^2*(lam2 - lam9 + 2*lameta)*sphi^2 + lam9*sphi^4), 0}},

C[ S[5] , S[5] , -S[5] , -S[5] ] == {{(-2*I)*(2*cphi^4*lameta + 2*cphi^2*lam9*sphi^2 + lam2*sphi^4), 0}},

C[ -S[7] , S[3] , S[5] ] == {{(-(Sqrt[2]*cphi*muzee) + (-lam4 + lam5)*sphi*vev)/2, 0}},

C[ -S[7] , S[2] , S[5] ] == {{(-I/2)*(Sqrt[2]*cab*cphi*muzee + cab*(lam4 + lam5)*sphi*vev - 2*lam6*sab*sphi*vev), 0}},

C[ S[7] , S[3] , -S[5] ] == {{(Sqrt[2]*cphi*muzee + (lam4 - lam5)*sphi*vev)/2, 0}},

C[ S[7] , S[2] , -S[5] ] == {{(-I/2)*(Sqrt[2]*cab*cphi*muzee + cab*(lam4 + lam5)*sphi*vev - 2*lam6*sab*sphi*vev), 0}},

C[ S[6] , -S[5] , S[4] ] == {{-((muzee*(cphi^2 + sphi^2))/Sqrt[2]), 0}},

C[ S[1] , -S[5] , S[4] ] == {{(I/2)*(2*cphi*(lam10 - lam7)*sab*sphi*vev + cab*(Sqrt[2]*cphi^2*muzee - Sqrt[2]*muzee*sphi^2 + 2*cphi*(-lam3 + lam8)*sphi*vev)), 0}},

C[ S[6] , S[5] , -S[4] ] == {{(muzee*(cphi^2 + sphi^2))/Sqrt[2], 0}},

C[ S[1] , S[5] , -S[4] ] == {{(I/2)*(2*cphi*(lam10 - lam7)*sab*sphi*vev + cab*(Sqrt[2]*cphi^2*muzee - Sqrt[2]*muzee*sphi^2 + 2*cphi*(-lam3 + lam8)*sphi*vev)), 0}},

C[ -S[7] , S[3] , S[2] , S[4] ] == {{(cphi*(lam4 - lam5)*sab)/2, 0}},

C[ S[6] , -S[7] , S[1] , S[4] ] == {{(cphi*(lam4 - lam5)*sab)/2, 0}},

C[ S[7] , S[3] , S[2] , -S[4] ] == {{-(cphi*(lam4 - lam5)*sab)/2, 0}},

C[ S[6] , S[7] , S[1] , -S[4] ] == {{-(cphi*(lam4 - lam5)*sab)/2, 0}},

C[ -S[7] , S[1] , S[5] ] == {{(-I/2)*(Sqrt[2]*cphi*muzee*sab + (2*cab*lam6 + (lam4 + lam5)*sab)*sphi*vev), 0}},

C[ S[7] , S[1] , -S[5] ] == {{(-I/2)*(Sqrt[2]*cphi*muzee*sab + (2*cab*lam6 + (lam4 + lam5)*sab)*sphi*vev), 0}},

C[ S[2] , -S[5] , S[4] ] == {{(-I/2)*(Sqrt[2]*cphi^2*muzee*sab - Sqrt[2]*muzee*sab*sphi^2 - 2*cphi*(cab*(lam10 - lam7) + (lam3 - lam8)*sab)*sphi*vev), 0}},

C[ S[2] , S[5] , -S[4] ] == {{(-I/2)*(Sqrt[2]*cphi^2*muzee*sab - Sqrt[2]*muzee*sab*sphi^2 - 2*cphi*(cab*(lam10 - lam7) + (lam3 - lam8)*sab)*sphi*vev), 0}},

C[ -S[7] , S[5] , S[5] , -S[5] ] == {{(-2*I)*sphi*(cphi^2*lam10 + lam7*sphi^2), 0}},

C[ S[7] , S[5] , -S[5] , -S[5] ] == {{(-2*I)*sphi*(cphi^2*lam10 + lam7*sphi^2), 0}},

C[ S[6] , S[3] , -S[5] , S[4] ] == {{I*cphi*(lam10 - lam7)*sphi, 0}},

C[ S[2] , S[1] , -S[5] , S[4] ] == {{I*cphi*(cab^2*(lam10 - lam7) + cab*(-lam2 + lam3 - lam8 + lam9)*sab + (-lam10 + lam7)*sab^2)*sphi, 0}},

C[ -S[7] , -S[5] , S[4] , S[4] ] == {{(2*I)*cphi^2*(lam10 - lam7)*sphi, 0}},

C[ S[6] , S[3] , S[5] , -S[4] ] == {{I*cphi*(lam10 - lam7)*sphi, 0}},

C[ S[2] , S[1] , S[5] , -S[4] ] == {{I*cphi*(cab^2*(lam10 - lam7) + cab*(-lam2 + lam3 - lam8 + lam9)*sab + (-lam10 + lam7)*sab^2)*sphi, 0}},

C[ -S[7] , S[5] , S[4] , -S[4] ] == {{(-I)*sphi*(-(cphi^2*(lam10 - 2*lam7)) + lam10*sphi^2), 0}},

C[ S[7] , -S[5] , S[4] , -S[4] ] == {{(-I)*sphi*(-(cphi^2*(lam10 - 2*lam7)) + lam10*sphi^2), 0}},

C[ S[7] , S[5] , -S[4] , -S[4] ] == {{(2*I)*cphi^2*(lam10 - lam7)*sphi, 0}},

C[ S[3] , S[3] , -S[5] , S[4] ] == {{(-I)*cphi*(lam2 - lam9)*sphi, 0}},

C[ S[2] , S[2] , -S[5] , S[4] ] == {{(-I)*cphi*(cab^2*(lam2 - lam9) + 2*cab*(lam10 - lam7)*sab + (lam3 - lam8)*sab^2)*sphi, 0}},

C[ S[3] , S[3] , S[5] , -S[4] ] == {{(-I)*cphi*(lam2 - lam9)*sphi, 0}},

C[ S[2] , S[2] , S[5] , -S[4] ] == {{(-I)*cphi*(cab^2*(lam2 - lam9) + 2*cab*(lam10 - lam7)*sab + (lam3 - lam8)*sab^2)*sphi, 0}},

C[ -S[5] , S[4] , S[4] , -S[4] ] == {{(-2*I)*cphi*sphi*(cphi^2*(lam2 - lam9) + (lam9 - 2*lameta)*sphi^2), 0}},

C[ S[5] , S[4] , -S[4] , -S[4] ] == {{(-2*I)*cphi*sphi*(cphi^2*(lam2 - lam9) + (lam9 - 2*lameta)*sphi^2), 0}},

C[ S[6] , S[6] , -S[5] , S[4] ] == {{(-I)*cphi*(lam3 - lam8)*sphi, 0}},

C[ S[7] , -S[7] , -S[5] , S[4] ] == {{(-I)*cphi*(lam3 + lam4 - lam8)*sphi, 0}},

C[ S[1] , S[1] , -S[5] , S[4] ] == {{(-I)*cphi*(cab^2*(lam3 - lam8) + 2*cab*(-lam10 + lam7)*sab + (lam2 - lam9)*sab^2)*sphi, 0}},

C[ S[6] , S[6] , S[5] , -S[4] ] == {{(-I)*cphi*(lam3 - lam8)*sphi, 0}},

C[ S[7] , -S[7] , S[5] , -S[4] ] == {{(-I)*cphi*(lam3 + lam4 - lam8)*sphi, 0}},

C[ S[1] , S[1] , S[5] , -S[4] ] == {{(-I)*cphi*(cab^2*(lam3 - lam8) + 2*cab*(-lam10 + lam7)*sab + (lam2 - lam9)*sab^2)*sphi, 0}},

C[ S[6] , -S[7] , S[3] , S[5] ] == {{(-I/2)*(lam4 + lam5)*sphi, 0}},

C[ S[6] , -S[7] , S[2] , S[5] ] == {{(cab*(lam4 - lam5)*sphi)/2, 0}},

C[ -S[7] , S[3] , S[1] , S[5] ] == {{-(cab*(lam4 - lam5)*sphi)/2, 0}},

C[ -S[7] , S[2] , S[1] , S[5] ] == {{(-I/2)*(cab^2*(lam4 + lam5) + 2*cab*(-lam6 + lam7)*sab - (lam4 + lam5)*sab^2)*sphi, 0}},

C[ S[6] , S[7] , S[3] , -S[5] ] == {{(-I/2)*(lam4 + lam5)*sphi, 0}},

C[ S[6] , S[7] , S[2] , -S[5] ] == {{-(cab*(lam4 - lam5)*sphi)/2, 0}},

C[ S[7] , S[3] , S[1] , -S[5] ] == {{(cab*(lam4 - lam5)*sphi)/2, 0}},

C[ S[7] , S[2] , S[1] , -S[5] ] == {{(-I/2)*(cab^2*(lam4 + lam5) + 2*cab*(-lam6 + lam7)*sab - (lam4 + lam5)*sab^2)*sphi, 0}},

C[ -S[7] , -S[7] , S[5] , S[4] ] == {{(-2*I)*cphi*lam5*sphi, 0}},

C[ S[7] , S[7] , -S[5] , -S[4] ] == {{(-2*I)*cphi*lam5*sphi, 0}},

C[ S[6] , S[6] , -S[7] , S[5] ] == {{(-I)*lam6*sphi, 0}},

C[ S[7] , -S[7] , -S[7] , S[5] ] == {{(-2*I)*lam6*sphi, 0}},

C[ -S[7] , S[1] , S[1] , S[5] ] == {{(-I)*(cab^2*lam6 + cab*(lam4 + lam5)*sab + lam7*sab^2)*sphi, 0}},

C[ S[6] , S[6] , S[7] , -S[5] ] == {{(-I)*lam6*sphi, 0}},

C[ S[7] , S[7] , -S[7] , -S[5] ] == {{(-2*I)*lam6*sphi, 0}},

C[ S[7] , S[1] , S[1] , -S[5] ] == {{(-I)*(cab^2*lam6 + cab*(lam4 + lam5)*sab + lam7*sab^2)*sphi, 0}},

C[ -S[7] , S[3] , S[3] , S[5] ] == {{(-I)*lam7*sphi, 0}},

C[ -S[7] , S[2] , S[2] , S[5] ] == {{(-I)*(cab^2*lam7 - cab*(lam4 + lam5)*sab + lam6*sab^2)*sphi, 0}},

C[ S[7] , S[3] , S[3] , -S[5] ] == {{(-I)*lam7*sphi, 0}},

C[ S[7] , S[2] , S[2] , -S[5] ] == {{(-I)*(cab^2*lam7 - cab*(lam4 + lam5)*sab + lam6*sab^2)*sphi, 0}},

C[ S[5] , -S[5] , -S[5] , S[4] ] == {{(-2*I)*cphi*sphi*(cphi^2*(lam9 - 2*lameta) + (lam2 - lam9)*sphi^2), 0}},

C[ S[5] , S[5] , -S[5] , -S[4] ] == {{(-2*I)*cphi*sphi*(cphi^2*(lam9 - 2*lameta) + (lam2 - lam9)*sphi^2), 0}},

C[ S[1] , S[5] , -S[5] ] == {{(-I)*(sab*(cphi^2*lam10 + lam7*sphi^2)*vev + cab*(-(Sqrt[2]*cphi*muzee*sphi) + cphi^2*lam8*vev + lam3*sphi^2*vev)), 0}},

C[ -S[7] , S[3] , S[4] ] == {{(Sqrt[2]*muzee*sphi + cphi*(-lam4 + lam5)*vev)/2, 0}},

C[ -S[7] , S[2] , S[4] ] == {{(I/2)*(Sqrt[2]*cab*muzee*sphi - cab*cphi*(lam4 + lam5)*vev + 2*cphi*lam6*sab*vev), 0}},

C[ S[7] , S[3] , -S[4] ] == {{(-(Sqrt[2]*muzee*sphi) + cphi*(lam4 - lam5)*vev)/2, 0}},

C[ S[7] , S[2] , -S[4] ] == {{(I/2)*(Sqrt[2]*cab*muzee*sphi - cab*cphi*(lam4 + lam5)*vev + 2*cphi*lam6*sab*vev), 0}},

C[ S[1] , S[4] , -S[4] ] == {{(-I)*(sab*(cphi^2*lam7 + lam10*sphi^2)*vev + cab*(Sqrt[2]*cphi*muzee*sphi + cphi^2*lam3*vev + lam8*sphi^2*vev)), 0}},

C[ -S[7] , S[3] , S[2] , S[5] ] == {{((lam4 - lam5)*sab*sphi)/2, 0}},

C[ S[6] , -S[7] , S[1] , S[5] ] == {{((lam4 - lam5)*sab*sphi)/2, 0}},

C[ S[7] , S[3] , S[2] , -S[5] ] == {{-((lam4 - lam5)*sab*sphi)/2, 0}},

C[ S[6] , S[7] , S[1] , -S[5] ] == {{-((lam4 - lam5)*sab*sphi)/2, 0}},

C[ S[2] , S[5] , -S[5] ] == {{(-I)*(Sqrt[2]*cphi*muzee*sab*sphi + cphi^2*(cab*lam10 - lam8*sab)*vev + (cab*lam7 - lam3*sab)*sphi^2*vev), 0}},

C[ -S[7] , S[1] , S[4] ] == {{(I/2)*(Sqrt[2]*muzee*sab*sphi - cphi*(2*cab*lam6 + (lam4 + lam5)*sab)*vev), 0}},

C[ S[7] , S[1] , -S[4] ] == {{(I/2)*(Sqrt[2]*muzee*sab*sphi - cphi*(2*cab*lam6 + (lam4 + lam5)*sab)*vev), 0}},

C[ S[2] , S[4] , -S[4] ] == {{I*(Sqrt[2]*cphi*muzee*sab*sphi + (-(cab*lam10) + lam8*sab)*sphi^2*vev + cphi^2*(-(cab*lam7*vev) + lam3*sab*vev)), 0}},

C[ S[7] , -S[5] , -S[5] , S[4] ] == {{(2*I)*cphi*(lam10 - lam7)*sphi^2, 0}},

C[ -S[7] , S[5] , S[5] , -S[4] ] == {{(2*I)*cphi*(lam10 - lam7)*sphi^2, 0}},

C[ -S[5] , -S[5] , S[4] , S[4] ] == {{(-2*I)*cphi^2*(lam2 - 2*lam9 + 2*lameta)*sphi^2, 0}},

C[ S[5] , S[5] , -S[4] , -S[4] ] == {{(-2*I)*cphi^2*(lam2 - 2*lam9 + 2*lameta)*sphi^2, 0}},

C[ -S[7] , -S[7] , S[5] , S[5] ] == {{(-2*I)*lam5*sphi^2, 0}},

C[ S[7] , S[7] , -S[5] , -S[5] ] == {{(-2*I)*lam5*sphi^2, 0}},

C[ S[6] , S[6] , S[1] ] == {{(-I)*(cab*lam1 + lam6*sab)*vev, 0}},

C[ S[7] , -S[7] , S[1] ] == {{(-I)*(cab*lam1 + lam6*sab)*vev, 0}},

C[ S[1] , S[1] , S[1] ] == {{(-3*I)*(cab^3*lam1 + 3*cab^2*lam6*sab + cab*(lam3 + lam4 + lam5)*sab^2 + lam7*sab^3)*vev, 0}},

C[ S[3] , S[3] , S[1] ] == {{(-I)*(cab*(lam3 + lam4 - lam5) + lam7*sab)*vev, 0}},

C[ S[2] , S[2] , S[1] ] == {{(-I)*(cab^3*(lam3 + lam4 + lam5) + 3*cab^2*(-2*lam6 + lam7)*sab + cab*(3*lam1 - 2*(lam3 + lam4 + lam5))*sab^2 + 3*lam6*sab^3)*vev, 0}},

C[ S[6] , S[3] , S[2] ] == {{(-I)*(cab*lam5 - lam6*sab)*vev, 0}},

C[ S[6] , S[6] , S[2] ] == {{(-I)*(cab*lam6 - lam1*sab)*vev, 0}},

C[ S[7] , -S[7] , S[2] ] == {{(-I)*(cab*lam6 - lam1*sab)*vev, 0}},

C[ S[6] , S[3] , S[1] ] == {{(-I)*(cab*lam6 + lam5*sab)*vev, 0}},

C[ S[2] , S[1] , S[1] ] == {{(-I)*(3*cab^3*lam6 + cab^2*(-3*lam1 + 2*(lam3 + lam4 + lam5))*sab + 3*cab*(-2*lam6 + lam7)*sab^2 - (lam3 + lam4 + lam5)*sab^3)*vev, 0}},

C[ S[3] , S[3] , S[2] ] == {{(-I)*(cab*lam7 - (lam3 + lam4 - lam5)*sab)*vev, 0}},

C[ S[2] , S[2] , S[2] ] == {{(-3*I)*(cab^3*lam7 - cab^2*(lam3 + lam4 + lam5)*sab + 3*cab*lam6*sab^2 - lam1*sab^3)*vev, 0}},

C[ S[7] , -S[7] , V[1] , V[1] ] == {{(2*I)*EL^2, 0}},

C[ S[5] , -S[5] , V[1] , V[1] ] == {{2*EL^2*(cphi + I*sphi)*(I*cphi + sphi), 0}},

C[ S[4] , -S[4] , V[1] , V[1] ] == {{2*EL^2*(cphi + I*sphi)*(I*cphi + sphi), 0}},

C[ S[7] , -S[7] , V[1] ] == {{(-I)*gc171, 0}, {I*gc171, 0}},

C[ S[5] , -S[5] , V[1] ] == {{(-I)*gc172, 0}, {I*gc172, 0}},

C[ S[4] , -S[4] , V[1] ] == {{(-I)*gc173, 0}, {I*gc173, 0}},

C[ S[6] , -S[7] , V[1] , V[3] ] == {{-EL^2/(2*sw), 0}},

C[ -S[7] , S[1] , V[1] , V[3] ] == {{((I/2)*cab*EL^2)/sw, 0}},

C[ S[3] , -S[4] , V[1] , V[3] ] == {{-(cphi*EL^2)/(2*sw), 0}},

C[ S[2] , -S[4] , V[1] , V[3] ] == {{((I/2)*cab*cphi*EL^2)/sw, 0}},

C[ -S[7] , S[2] , V[1] , V[3] ] == {{((-I/2)*EL^2*sab)/sw, 0}},

C[ S[1] , -S[4] , V[1] , V[3] ] == {{((I/2)*cphi*EL^2*sab)/sw, 0}},

C[ S[3] , -S[5] , V[1] , V[3] ] == {{-(EL^2*sphi)/(2*sw), 0}},

C[ S[2] , -S[5] , V[1] , V[3] ] == {{((I/2)*cab*EL^2*sphi)/sw, 0}},

C[ S[1] , -S[5] , V[1] , V[3] ] == {{((I/2)*EL^2*sab*sphi)/sw, 0}},

C[ -S[7] , V[1] , V[3] ] == {{((I/2)*EL^2*vev)/sw, 0}},

C[ S[6] , -S[7] , V[3] ] == {{-gc184, 0}, {gc184, 0}},

C[ -S[7] , S[1] , V[3] ] == {{(-I)*gc185, 0}, {I*gc185, 0}},

C[ -S[7] , S[2] , V[3] ] == {{(-I)*gc186, 0}, {I*gc186, 0}},

C[ S[3] , -S[4] , V[3] ] == {{-gc187, 0}, {gc187, 0}},

C[ S[3] , -S[5] , V[3] ] == {{-gc188, 0}, {gc188, 0}},

C[ S[2] , -S[4] , V[3] ] == {{(-I)*gc189, 0}, {I*gc189, 0}},

C[ S[2] , -S[5] , V[3] ] == {{(-I)*gc190, 0}, {I*gc190, 0}},

C[ S[1] , -S[4] , V[3] ] == {{(-I)*gc191, 0}, {I*gc191, 0}},

C[ S[1] , -S[5] , V[3] ] == {{(-I)*gc192, 0}, {I*gc192, 0}},

C[ S[6] , S[7] , V[1] , -V[3] ] == {{EL^2/(2*sw), 0}},

C[ S[7] , S[1] , V[1] , -V[3] ] == {{((I/2)*cab*EL^2)/sw, 0}},

C[ S[3] , S[4] , V[1] , -V[3] ] == {{(cphi*EL^2)/(2*sw), 0}},

C[ S[2] , S[4] , V[1] , -V[3] ] == {{((I/2)*cab*cphi*EL^2)/sw, 0}},

C[ S[7] , S[2] , V[1] , -V[3] ] == {{((-I/2)*EL^2*sab)/sw, 0}},

C[ S[1] , S[4] , V[1] , -V[3] ] == {{((I/2)*cphi*EL^2*sab)/sw, 0}},

C[ S[3] , S[5] , V[1] , -V[3] ] == {{(EL^2*sphi)/(2*sw), 0}},

C[ S[2] , S[5] , V[1] , -V[3] ] == {{((I/2)*cab*EL^2*sphi)/sw, 0}},

C[ S[1] , S[5] , V[1] , -V[3] ] == {{((I/2)*EL^2*sab*sphi)/sw, 0}},

C[ S[7] , V[1] , -V[3] ] == {{((I/2)*EL^2*vev)/sw, 0}},

C[ S[6] , S[7] , -V[3] ] == {{-gc203, 0}, {gc203, 0}},

C[ S[7] , S[1] , -V[3] ] == {{(-I)*gc204, 0}, {I*gc204, 0}},

C[ S[7] , S[2] , -V[3] ] == {{(-I)*gc205, 0}, {I*gc205, 0}},

C[ S[3] , S[4] , -V[3] ] == {{-gc206, 0}, {gc206, 0}},

C[ S[3] , S[5] , -V[3] ] == {{-gc207, 0}, {gc207, 0}},

C[ S[2] , S[4] , -V[3] ] == {{(-I)*gc208, 0}, {I*gc208, 0}},

C[ S[2] , S[5] , -V[3] ] == {{(-I)*gc209, 0}, {I*gc209, 0}},

C[ S[1] , S[4] , -V[3] ] == {{(-I)*gc210, 0}, {I*gc210, 0}},

C[ S[1] , S[5] , -V[3] ] == {{(-I)*gc211, 0}, {I*gc211, 0}},

C[ S[6] , S[6] , V[3] , -V[3] ] == {{((I/2)*EL^2)/sw^2, 0}},

C[ S[7] , -S[7] , V[3] , -V[3] ] == {{((I/2)*EL^2)/sw^2, 0}},

C[ S[3] , S[3] , V[3] , -V[3] ] == {{((I/2)*EL^2)/sw^2, 0}},

C[ S[2] , S[2] , V[3] , -V[3] ] == {{((I/2)*EL^2*(cab^2 + sab^2))/sw^2, 0}},

C[ S[1] , S[1] , V[3] , -V[3] ] == {{((I/2)*EL^2*(cab^2 + sab^2))/sw^2, 0}},

C[ S[4] , -S[4] , V[3] , -V[3] ] == {{((I/2)*cphi^2*EL^2)/sw^2, 0}},

C[ -S[5] , S[4] , V[3] , -V[3] ] == {{((I/2)*cphi*EL^2*sphi)/sw^2, 0}},

C[ S[5] , -S[4] , V[3] , -V[3] ] == {{((I/2)*cphi*EL^2*sphi)/sw^2, 0}},

C[ S[5] , -S[5] , V[3] , -V[3] ] == {{((I/2)*EL^2*sphi^2)/sw^2, 0}},

C[ S[1] , V[3] , -V[3] ] == {{((I/2)*cab*EL^2*vev)/sw^2, 0}},

C[ S[2] , V[3] , -V[3] ] == {{((-I/2)*EL^2*sab*vev)/sw^2, 0}},

C[ S[7] , -S[7] , V[1] , V[2] ] == {{(I*EL^2*(cw - sw)*(cw + sw))/(cw*sw), 0}},

C[ S[4] , -S[4] , V[1] , V[2] ] == {{(I*EL^2*(-2*sphi^2*sw^2 + cphi^2*(cw^2 - sw^2)))/(cw*sw), 0}},

C[ -S[5] , S[4] , V[1] , V[2] ] == {{(I*cphi*EL^2*sphi*(cw^2 + sw^2))/(cw*sw), 0}},

C[ S[5] , -S[4] , V[1] , V[2] ] == {{(I*cphi*EL^2*sphi*(cw^2 + sw^2))/(cw*sw), 0}},

C[ S[5] , -S[5] , V[1] , V[2] ] == {{(I*EL^2*(cw^2*sphi^2 - (2*cphi^2 + sphi^2)*sw^2))/(cw*sw), 0}},

C[ S[6] , S[1] , V[2] ] == {{-gc228, 0}, {gc228, 0}},

C[ S[6] , S[2] , V[2] ] == {{-gc229, 0}, {gc229, 0}},

C[ S[7] , -S[7] , V[2] ] == {{(-I)*gc230, 0}, {I*gc230, 0}},

C[ S[3] , S[2] , V[2] ] == {{-gc231, 0}, {gc231, 0}},

C[ S[3] , S[1] , V[2] ] == {{-gc232, 0}, {gc232, 0}},

C[ S[5] , -S[4] , V[2] ] == {{(-I)*gc233, 0}, {I*gc233, 0}},

C[ S[5] , -S[5] , V[2] ] == {{I*gc234*(cw^2*sphi^2 - (2*cphi^2 + sphi^2)*sw^2), 0}, {(-I)*gc234*(cw^2*sphi^2 - (2*cphi^2 + sphi^2)*sw^2), 0}},

C[ -S[5] , S[4] , V[2] ] == {{(-I)*gc235, 0}, {I*gc235, 0}},

C[ S[4] , -S[4] , V[2] ] == {{(-I)*gc236, 0}, {I*gc236, 0}},

C[ S[6] , -S[7] , V[3] , V[2] ] == {{EL^2/(2*cw), 0}},

C[ -S[7] , S[1] , V[3] , V[2] ] == {{((-I/2)*cab*EL^2)/cw, 0}},

C[ S[3] , -S[4] , V[3] , V[2] ] == {{(cphi*EL^2)/(2*cw), 0}},

C[ S[2] , -S[4] , V[3] , V[2] ] == {{((-I/2)*cab*cphi*EL^2)/cw, 0}},

C[ -S[7] , S[2] , V[3] , V[2] ] == {{((I/2)*EL^2*sab)/cw, 0}},

C[ S[1] , -S[4] , V[3] , V[2] ] == {{((-I/2)*cphi*EL^2*sab)/cw, 0}},

C[ S[3] , -S[5] , V[3] , V[2] ] == {{(EL^2*sphi)/(2*cw), 0}},

C[ S[2] , -S[5] , V[3] , V[2] ] == {{((-I/2)*cab*EL^2*sphi)/cw, 0}},

C[ S[1] , -S[5] , V[3] , V[2] ] == {{((-I/2)*EL^2*sab*sphi)/cw, 0}},

C[ -S[7] , V[3] , V[2] ] == {{((-I/2)*EL^2*vev)/cw, 0}},

C[ S[6] , S[7] , -V[3] , V[2] ] == {{-EL^2/(2*cw), 0}},

C[ S[7] , S[1] , -V[3] , V[2] ] == {{((-I/2)*cab*EL^2)/cw, 0}},

C[ S[3] , S[4] , -V[3] , V[2] ] == {{-(cphi*EL^2)/(2*cw), 0}},

C[ S[2] , S[4] , -V[3] , V[2] ] == {{((-I/2)*cab*cphi*EL^2)/cw, 0}},

C[ S[7] , S[2] , -V[3] , V[2] ] == {{((I/2)*EL^2*sab)/cw, 0}},

C[ S[1] , S[4] , -V[3] , V[2] ] == {{((-I/2)*cphi*EL^2*sab)/cw, 0}},

C[ S[3] , S[5] , -V[3] , V[2] ] == {{-(EL^2*sphi)/(2*cw), 0}},

C[ S[2] , S[5] , -V[3] , V[2] ] == {{((-I/2)*cab*EL^2*sphi)/cw, 0}},

C[ S[1] , S[5] , -V[3] , V[2] ] == {{((-I/2)*EL^2*sab*sphi)/cw, 0}},

C[ S[7] , -V[3] , V[2] ] == {{((-I/2)*EL^2*vev)/cw, 0}},

C[ S[6] , S[6] , V[2] , V[2] ] == {{((I/2)*EL^2*(cw^2 + sw^2)^2)/(cw^2*sw^2), 0}},

C[ S[7] , -S[7] , V[2] , V[2] ] == {{((I/2)*EL^2*(cw - sw)^2*(cw + sw)^2)/(cw^2*sw^2), 0}},

C[ S[3] , S[3] , V[2] , V[2] ] == {{((I/2)*EL^2*(cw^2 + sw^2)^2)/(cw^2*sw^2), 0}},

C[ S[2] , S[2] , V[2] , V[2] ] == {{((I/2)*EL^2*(cab^2 + sab^2)*(cw^2 + sw^2)^2)/(cw^2*sw^2), 0}},

C[ S[1] , S[1] , V[2] , V[2] ] == {{((I/2)*EL^2*(cab^2 + sab^2)*(cw^2 + sw^2)^2)/(cw^2*sw^2), 0}},

C[ S[4] , -S[4] , V[2] , V[2] ] == {{((I/2)*EL^2*(4*sphi^2*sw^4 + cphi^2*(cw^2 - sw^2)^2))/(cw^2*sw^2), 0}},

C[ -S[5] , S[4] , V[2] , V[2] ] == {{((I/2)*cphi*EL^2*sphi*(cw^2 - 3*sw^2)*(cw^2 + sw^2))/(cw^2*sw^2), 0}},

C[ S[5] , -S[4] , V[2] , V[2] ] == {{((I/2)*cphi*EL^2*sphi*(cw^2 - 3*sw^2)*(cw^2 + sw^2))/(cw^2*sw^2), 0}},

C[ S[5] , -S[5] , V[2] , V[2] ] == {{((I/2)*EL^2*(cw^4*sphi^2 - 2*cw^2*sphi^2*sw^2 + (4*cphi^2 + sphi^2)*sw^4))/(cw^2*sw^2), 0}},

C[ S[1] , V[2] , V[2] ] == {{((I/2)*cab*EL^2*(cw^2 + sw^2)^2*vev)/(cw^2*sw^2), 0}},

C[ S[2] , V[2] , V[2] ] == {{((-I/2)*EL^2*sab*(cw^2 + sw^2)^2*vev)/(cw^2*sw^2), 0}},

C[ -F[4] , F[4] , V[1] ] == {{I*gc268, 0}, {I*gc268, 0}},

C[ -F[5] , F[5] , V[1] ] == {{I*gc269, 0}, {I*gc269, 0}},

C[ -F[6] , F[6] , V[1] ] == {{I*gc270, 0}, {I*gc270, 0}},

C[ -F[8, {e1x2}] , F[8, {e2x2}] , V[1] ] == {{I*gc271*IndexDelta[e1x2, e2x2], 0}, {I*gc271*IndexDelta[e1x2, e2x2], 0}},

C[ -F[9, {e1x2}] , F[9, {e2x2}] , V[1] ] == {{I*gc272*IndexDelta[e1x2, e2x2], 0}, {I*gc272*IndexDelta[e1x2, e2x2], 0}},

C[ -F[7, {e1x2}] , F[7, {e2x2}] , V[1] ] == {{I*gc273*IndexDelta[e1x2, e2x2], 0}, {I*gc273*IndexDelta[e1x2, e2x2], 0}},

C[ -F[12, {e1x2}] , F[12, {e2x2}] , V[1] ] == {{I*gc274*IndexDelta[e1x2, e2x2], 0}, {I*gc274*IndexDelta[e1x2, e2x2], 0}},

C[ -F[10, {e1x2}] , F[10, {e2x2}] , V[1] ] == {{I*gc275*IndexDelta[e1x2, e2x2], 0}, {I*gc275*IndexDelta[e1x2, e2x2], 0}},

C[ -F[11, {e1x2}] , F[11, {e2x2}] , V[1] ] == {{I*gc276*IndexDelta[e1x2, e2x2], 0}, {I*gc276*IndexDelta[e1x2, e2x2], 0}},

C[ -F[8, {e1x2}] , F[8, {e2x2}] , V[4, {e3x2}] ] == {{I*gc277*SUNT[e3x2, e1x2, e2x2], 0}, {I*gc277*SUNT[e3x2, e1x2, e2x2], 0}},

C[ -F[9, {e1x2}] , F[9, {e2x2}] , V[4, {e3x2}] ] == {{I*gc278*SUNT[e3x2, e1x2, e2x2], 0}, {I*gc278*SUNT[e3x2, e1x2, e2x2], 0}},

C[ -F[7, {e1x2}] , F[7, {e2x2}] , V[4, {e3x2}] ] == {{I*gc279*SUNT[e3x2, e1x2, e2x2], 0}, {I*gc279*SUNT[e3x2, e1x2, e2x2], 0}},

C[ -F[12, {e1x2}] , F[12, {e2x2}] , V[4, {e3x2}] ] == {{I*gc280*SUNT[e3x2, e1x2, e2x2], 0}, {I*gc280*SUNT[e3x2, e1x2, e2x2], 0}},

C[ -F[10, {e1x2}] , F[10, {e2x2}] , V[4, {e3x2}] ] == {{I*gc281*SUNT[e3x2, e1x2, e2x2], 0}, {I*gc281*SUNT[e3x2, e1x2, e2x2], 0}},

C[ -F[11, {e1x2}] , F[11, {e2x2}] , V[4, {e3x2}] ] == {{I*gc282*SUNT[e3x2, e1x2, e2x2], 0}, {I*gc282*SUNT[e3x2, e1x2, e2x2], 0}},

C[ -F[8, {e1x2}] , F[12, {e2x2}] , V[3] ] == {{I*gc283*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[8, {e1x2}] , F[10, {e2x2}] , V[3] ] == {{I*gc284*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[8, {e1x2}] , F[11, {e2x2}] , V[3] ] == {{I*gc285*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[9, {e1x2}] , F[12, {e2x2}] , V[3] ] == {{I*gc286*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[9, {e1x2}] , F[10, {e2x2}] , V[3] ] == {{I*gc287*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[9, {e1x2}] , F[11, {e2x2}] , V[3] ] == {{I*gc288*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[7, {e1x2}] , F[12, {e2x2}] , V[3] ] == {{I*gc289*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[7, {e1x2}] , F[10, {e2x2}] , V[3] ] == {{I*gc290*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[7, {e1x2}] , F[11, {e2x2}] , V[3] ] == {{I*gc291*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[12, {e1x2}] , F[8, {e2x2}] , -V[3] ] == {{I*gc292*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[12, {e1x2}] , F[9, {e2x2}] , -V[3] ] == {{I*gc293*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[12, {e1x2}] , F[7, {e2x2}] , -V[3] ] == {{I*gc294*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[10, {e1x2}] , F[8, {e2x2}] , -V[3] ] == {{I*gc295*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[10, {e1x2}] , F[9, {e2x2}] , -V[3] ] == {{I*gc296*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[10, {e1x2}] , F[7, {e2x2}] , -V[3] ] == {{I*gc297*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[11, {e1x2}] , F[8, {e2x2}] , -V[3] ] == {{I*gc298*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[11, {e1x2}] , F[9, {e2x2}] , -V[3] ] == {{I*gc299*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[11, {e1x2}] , F[7, {e2x2}] , -V[3] ] == {{I*gc300*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[1] , F[4] , V[3] ] == {{I*gc301, 0}, {0, 0}},

C[ -F[2] , F[5] , V[3] ] == {{I*gc302, 0}, {0, 0}},

C[ -F[3] , F[6] , V[3] ] == {{I*gc303, 0}, {0, 0}},

C[ -F[4] , F[1] , -V[3] ] == {{I*gc304, 0}, {0, 0}},

C[ -F[5] , F[2] , -V[3] ] == {{I*gc305, 0}, {0, 0}},

C[ -F[6] , F[3] , -V[3] ] == {{I*gc306, 0}, {0, 0}},

C[ -F[8, {e1x2}] , F[8, {e2x2}] , V[2] ] == {{I*gc307L*IndexDelta[e1x2, e2x2], 0}, {I*gc307R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[9, {e1x2}] , F[9, {e2x2}] , V[2] ] == {{I*gc308L*IndexDelta[e1x2, e2x2], 0}, {I*gc308R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[7, {e1x2}] , F[7, {e2x2}] , V[2] ] == {{I*gc309L*IndexDelta[e1x2, e2x2], 0}, {I*gc309R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[12, {e1x2}] , F[12, {e2x2}] , V[2] ] == {{I*gc310L*IndexDelta[e1x2, e2x2], 0}, {I*gc310R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[10, {e1x2}] , F[10, {e2x2}] , V[2] ] == {{I*gc311L*IndexDelta[e1x2, e2x2], 0}, {I*gc311R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[11, {e1x2}] , F[11, {e2x2}] , V[2] ] == {{I*gc312L*IndexDelta[e1x2, e2x2], 0}, {I*gc312R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[1] , F[1] , V[2] ] == {{I*gc313, 0}, {0, 0}},

C[ -F[2] , F[2] , V[2] ] == {{I*gc314, 0}, {0, 0}},

C[ -F[3] , F[3] , V[2] ] == {{I*gc315, 0}, {0, 0}},

C[ -F[4] , F[4] , V[2] ] == {{I*gc316L, 0}, {I*gc316R, 0}},

C[ -F[5] , F[5] , V[2] ] == {{I*gc317L, 0}, {I*gc317R, 0}},

C[ -F[6] , F[6] , V[2] ] == {{I*gc318L, 0}, {I*gc318R, 0}},

C[ -F[12, {e1x2}] , F[8, {e2x2}] , -S[7] ] == {{I*gc319L*IndexDelta[e1x2, e2x2], 0}, {I*gc319R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[12, {e1x2}] , F[9, {e2x2}] , -S[7] ] == {{I*gc320L*IndexDelta[e1x2, e2x2], 0}, {I*gc320R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[12, {e1x2}] , F[7, {e2x2}] , -S[7] ] == {{I*gc321L*IndexDelta[e1x2, e2x2], 0}, {I*gc321R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[10, {e1x2}] , F[8, {e2x2}] , -S[7] ] == {{I*gc322L*IndexDelta[e1x2, e2x2], 0}, {I*gc322R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[10, {e1x2}] , F[9, {e2x2}] , -S[7] ] == {{I*gc323L*IndexDelta[e1x2, e2x2], 0}, {I*gc323R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[10, {e1x2}] , F[7, {e2x2}] , -S[7] ] == {{I*gc324L*IndexDelta[e1x2, e2x2], 0}, {I*gc324R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[11, {e1x2}] , F[8, {e2x2}] , -S[7] ] == {{I*gc325L*IndexDelta[e1x2, e2x2], 0}, {I*gc325R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[11, {e1x2}] , F[9, {e2x2}] , -S[7] ] == {{I*gc326L*IndexDelta[e1x2, e2x2], 0}, {I*gc326R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[11, {e1x2}] , F[7, {e2x2}] , -S[7] ] == {{I*gc327L*IndexDelta[e1x2, e2x2], 0}, {I*gc327R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[12, {e1x2}] , F[12, {e2x2}] , S[6] ] == {{gc328L*IndexDelta[e1x2, e2x2], 0}, {gc328R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[10, {e1x2}] , F[10, {e2x2}] , S[6] ] == {{gc329L*IndexDelta[e1x2, e2x2], 0}, {gc329R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[11, {e1x2}] , F[11, {e2x2}] , S[6] ] == {{gc330L*IndexDelta[e1x2, e2x2], 0}, {gc330R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[12, {e1x2}] , F[12, {e2x2}] , S[1] ] == {{I*gc331*IndexDelta[e1x2, e2x2], 0}, {I*gc331*IndexDelta[e1x2, e2x2], 0}},

C[ -F[10, {e1x2}] , F[10, {e2x2}] , S[1] ] == {{I*gc332*IndexDelta[e1x2, e2x2], 0}, {I*gc332*IndexDelta[e1x2, e2x2], 0}},

C[ -F[11, {e1x2}] , F[11, {e2x2}] , S[1] ] == {{I*gc333*IndexDelta[e1x2, e2x2], 0}, {I*gc333*IndexDelta[e1x2, e2x2], 0}},

C[ -F[12, {e1x2}] , F[12, {e2x2}] , S[2] ] == {{I*gc334*IndexDelta[e1x2, e2x2], 0}, {I*gc334*IndexDelta[e1x2, e2x2], 0}},

C[ -F[10, {e1x2}] , F[10, {e2x2}] , S[2] ] == {{I*gc335*IndexDelta[e1x2, e2x2], 0}, {I*gc335*IndexDelta[e1x2, e2x2], 0}},

C[ -F[11, {e1x2}] , F[11, {e2x2}] , S[2] ] == {{I*gc336*IndexDelta[e1x2, e2x2], 0}, {I*gc336*IndexDelta[e1x2, e2x2], 0}},

C[ -F[4] , F[1] , -S[7] ] == {{I*gc337, 0}, {0, 0}},

C[ -F[5] , F[2] , -S[7] ] == {{I*gc338, 0}, {0, 0}},

C[ -F[6] , F[3] , -S[7] ] == {{I*gc339, 0}, {0, 0}},

C[ -F[4] , F[4] , S[6] ] == {{gc340L, 0}, {gc340R, 0}},

C[ -F[5] , F[5] , S[6] ] == {{gc341L, 0}, {gc341R, 0}},

C[ -F[6] , F[6] , S[6] ] == {{gc342L, 0}, {gc342R, 0}},

C[ -F[4] , F[4] , S[1] ] == {{I*gc343, 0}, {I*gc343, 0}},

C[ -F[5] , F[5] , S[1] ] == {{I*gc344, 0}, {I*gc344, 0}},

C[ -F[6] , F[6] , S[1] ] == {{I*gc345, 0}, {I*gc345, 0}},

C[ -F[4] , F[4] , S[2] ] == {{I*gc346, 0}, {I*gc346, 0}},

C[ -F[5] , F[5] , S[2] ] == {{I*gc347, 0}, {I*gc347, 0}},

C[ -F[6] , F[6] , S[2] ] == {{I*gc348, 0}, {I*gc348, 0}},

C[ -F[4] , F[1] , -S[4] ] == {{I*gc349, 0}, {0, 0}},

C[ -F[4] , F[2] , -S[4] ] == {{I*gc350L, 0}, {I*gc350R, 0}},

C[ -F[4] , F[3] , -S[4] ] == {{I*gc351L, 0}, {I*gc351R, 0}},

C[ -F[5] , F[1] , -S[4] ] == {{I*gc352L, 0}, {I*gc352R, 0}},

C[ -F[5] , F[2] , -S[4] ] == {{I*gc353, 0}, {0, 0}},

C[ -F[5] , F[3] , -S[4] ] == {{I*gc354L, 0}, {I*gc354R, 0}},

C[ -F[6] , F[1] , -S[4] ] == {{I*gc355L, 0}, {I*gc355R, 0}},

C[ -F[6] , F[2] , -S[4] ] == {{I*gc356L, 0}, {I*gc356R, 0}},

C[ -F[6] , F[3] , -S[4] ] == {{I*gc357, 0}, {0, 0}},

C[ -F[4] , F[1] , -S[5] ] == {{I*gc358, 0}, {0, 0}},

C[ -F[4] , F[2] , -S[5] ] == {{I*gc359L, 0}, {I*gc359R, 0}},

C[ -F[4] , F[3] , -S[5] ] == {{I*gc360L, 0}, {I*gc360R, 0}},

C[ -F[5] , F[1] , -S[5] ] == {{I*gc361L, 0}, {I*gc361R, 0}},

C[ -F[5] , F[2] , -S[5] ] == {{I*gc362, 0}, {0, 0}},

C[ -F[5] , F[3] , -S[5] ] == {{I*gc363L, 0}, {I*gc363R, 0}},

C[ -F[6] , F[1] , -S[5] ] == {{I*gc364L, 0}, {I*gc364R, 0}},

C[ -F[6] , F[2] , -S[5] ] == {{I*gc365L, 0}, {I*gc365R, 0}},

C[ -F[6] , F[3] , -S[5] ] == {{I*gc366, 0}, {0, 0}},

C[ -F[4] , F[4] , S[3] ] == {{gc367L, 0}, {gc367R, 0}},

C[ -F[4] , F[5] , S[3] ] == {{gc368L, 0}, {gc368R, 0}},

C[ -F[4] , F[6] , S[3] ] == {{gc369L, 0}, {gc369R, 0}},

C[ -F[5] , F[4] , S[3] ] == {{gc370L, 0}, {gc370R, 0}},

C[ -F[5] , F[5] , S[3] ] == {{gc371L, 0}, {gc371R, 0}},

C[ -F[5] , F[6] , S[3] ] == {{gc372L, 0}, {gc372R, 0}},

C[ -F[6] , F[4] , S[3] ] == {{gc373L, 0}, {gc373R, 0}},

C[ -F[6] , F[5] , S[3] ] == {{gc374L, 0}, {gc374R, 0}},

C[ -F[6] , F[6] , S[3] ] == {{gc375L, 0}, {gc375R, 0}},

C[ -F[4] , F[5] , S[2] ] == {{I*gc376L, 0}, {I*gc376R, 0}},

C[ -F[4] , F[6] , S[2] ] == {{I*gc377L, 0}, {I*gc377R, 0}},

C[ -F[5] , F[4] , S[2] ] == {{I*gc378L, 0}, {I*gc378R, 0}},

C[ -F[5] , F[6] , S[2] ] == {{I*gc379L, 0}, {I*gc379R, 0}},

C[ -F[6] , F[4] , S[2] ] == {{I*gc380L, 0}, {I*gc380R, 0}},

C[ -F[6] , F[5] , S[2] ] == {{I*gc381L, 0}, {I*gc381R, 0}},

C[ -F[4] , F[5] , S[1] ] == {{I*gc382L, 0}, {I*gc382R, 0}},

C[ -F[4] , F[6] , S[1] ] == {{I*gc383L, 0}, {I*gc383R, 0}},

C[ -F[5] , F[4] , S[1] ] == {{I*gc384L, 0}, {I*gc384R, 0}},

C[ -F[5] , F[6] , S[1] ] == {{I*gc385L, 0}, {I*gc385R, 0}},

C[ -F[6] , F[4] , S[1] ] == {{I*gc386L, 0}, {I*gc386R, 0}},

C[ -F[6] , F[5] , S[1] ] == {{I*gc387L, 0}, {I*gc387R, 0}},

C[ -F[8, {e1x2}] , F[12, {e2x2}] , S[7] ] == {{I*gc388L*IndexDelta[e1x2, e2x2], 0}, {I*gc388R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[8, {e1x2}] , F[10, {e2x2}] , S[7] ] == {{I*gc389L*IndexDelta[e1x2, e2x2], 0}, {I*gc389R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[8, {e1x2}] , F[11, {e2x2}] , S[7] ] == {{I*gc390L*IndexDelta[e1x2, e2x2], 0}, {I*gc390R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[9, {e1x2}] , F[12, {e2x2}] , S[7] ] == {{I*gc391L*IndexDelta[e1x2, e2x2], 0}, {I*gc391R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[9, {e1x2}] , F[10, {e2x2}] , S[7] ] == {{I*gc392L*IndexDelta[e1x2, e2x2], 0}, {I*gc392R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[9, {e1x2}] , F[11, {e2x2}] , S[7] ] == {{I*gc393L*IndexDelta[e1x2, e2x2], 0}, {I*gc393R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[7, {e1x2}] , F[12, {e2x2}] , S[7] ] == {{I*gc394L*IndexDelta[e1x2, e2x2], 0}, {I*gc394R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[7, {e1x2}] , F[10, {e2x2}] , S[7] ] == {{I*gc395L*IndexDelta[e1x2, e2x2], 0}, {I*gc395R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[7, {e1x2}] , F[11, {e2x2}] , S[7] ] == {{I*gc396L*IndexDelta[e1x2, e2x2], 0}, {I*gc396R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[8, {e1x2}] , F[8, {e2x2}] , S[6] ] == {{gc397L*IndexDelta[e1x2, e2x2], 0}, {gc397R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[9, {e1x2}] , F[9, {e2x2}] , S[6] ] == {{gc398L*IndexDelta[e1x2, e2x2], 0}, {gc398R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[7, {e1x2}] , F[7, {e2x2}] , S[6] ] == {{gc399L*IndexDelta[e1x2, e2x2], 0}, {gc399R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[8, {e1x2}] , F[8, {e2x2}] , S[1] ] == {{I*gc400*IndexDelta[e1x2, e2x2], 0}, {I*gc400*IndexDelta[e1x2, e2x2], 0}},

C[ -F[9, {e1x2}] , F[9, {e2x2}] , S[1] ] == {{I*gc401*IndexDelta[e1x2, e2x2], 0}, {I*gc401*IndexDelta[e1x2, e2x2], 0}},

C[ -F[7, {e1x2}] , F[7, {e2x2}] , S[1] ] == {{I*gc402*IndexDelta[e1x2, e2x2], 0}, {I*gc402*IndexDelta[e1x2, e2x2], 0}},

C[ -F[8, {e1x2}] , F[8, {e2x2}] , S[2] ] == {{I*gc403*IndexDelta[e1x2, e2x2], 0}, {I*gc403*IndexDelta[e1x2, e2x2], 0}},

C[ -F[9, {e1x2}] , F[9, {e2x2}] , S[2] ] == {{I*gc404*IndexDelta[e1x2, e2x2], 0}, {I*gc404*IndexDelta[e1x2, e2x2], 0}},

C[ -F[7, {e1x2}] , F[7, {e2x2}] , S[2] ] == {{I*gc405*IndexDelta[e1x2, e2x2], 0}, {I*gc405*IndexDelta[e1x2, e2x2], 0}},

C[ -F[1] , F[5] , S[5] ] == {{I*gc406L, 0}, {I*gc406R, 0}},

C[ -F[1] , F[5] , S[4] ] == {{I*gc407L, 0}, {I*gc407R, 0}},

C[ -F[1] , F[6] , S[5] ] == {{I*gc408L, 0}, {I*gc408R, 0}},

C[ -F[1] , F[6] , S[4] ] == {{I*gc409L, 0}, {I*gc409R, 0}},

C[ -F[2] , F[4] , S[5] ] == {{I*gc410L, 0}, {I*gc410R, 0}},

C[ -F[2] , F[4] , S[4] ] == {{I*gc411L, 0}, {I*gc411R, 0}},

C[ -F[2] , F[6] , S[5] ] == {{I*gc412L, 0}, {I*gc412R, 0}},

C[ -F[2] , F[6] , S[4] ] == {{I*gc413L, 0}, {I*gc413R, 0}},

C[ -F[3] , F[4] , S[5] ] == {{I*gc414L, 0}, {I*gc414R, 0}},

C[ -F[3] , F[4] , S[4] ] == {{I*gc415L, 0}, {I*gc415R, 0}},

C[ -F[3] , F[5] , S[5] ] == {{I*gc416L, 0}, {I*gc416R, 0}},

C[ -F[3] , F[5] , S[4] ] == {{I*gc417L, 0}, {I*gc417R, 0}},

C[ -F[1] , F[4] , S[7] ] == {{0, 0}, {I*gc418R, 0}},

C[ -F[2] , F[5] , S[7] ] == {{0, 0}, {I*gc419R, 0}},

C[ -F[3] , F[6] , S[7] ] == {{0, 0}, {I*gc420R, 0}},

C[ -F[1] , F[4] , S[4] ] == {{0, 0}, {I*gc421R, 0}},

C[ -F[1] , F[4] , S[5] ] == {{0, 0}, {I*gc422R, 0}},

C[ -F[2] , F[5] , S[4] ] == {{0, 0}, {I*gc423R, 0}},

C[ -F[2] , F[5] , S[5] ] == {{0, 0}, {I*gc424R, 0}},

C[ -F[3] , F[6] , S[4] ] == {{0, 0}, {I*gc425R, 0}},

C[ -F[3] , F[6] , S[5] ] == {{0, 0}, {I*gc426R, 0}},

C[ -U[1] , U[4] , V[3] ] == {{I*gc427, 0}, {I*gc427, 0}, {0, 0}},

C[ -U[1] , U[3] , -V[3] ] == {{I*gc428, 0}, {I*gc428, 0}, {0, 0}},

C[ -S[7] , -U[4] , U[1] ] == {{(EL^2*vev)/(2*sw), 0}},

C[ -U[4] , U[1] , -V[3] ] == {{I*gc430, 0}, {I*gc430, 0}, {0, 0}},

C[ -U[4] , U[4] , V[1] ] == {{I*gc431, 0}, {I*gc431, 0}, {0, 0}},

C[ -U[4] , U[4] , V[2] ] == {{I*gc432, 0}, {I*gc432, 0}, {0, 0}},

C[ -S[7] , -U[4] , U[2] ] == {{(EL^2*(cw - sw)*(cw + sw)*vev)/(4*cw*sw^2), 0}},

C[ -U[4] , U[2] , -V[3] ] == {{I*gc434, 0}, {I*gc434, 0}, {0, 0}},

C[ S[7] , -U[3] , U[1] ] == {{-(EL^2*vev)/(2*sw), 0}},

C[ -U[3] , U[1] , V[3] ] == {{I*gc436, 0}, {I*gc436, 0}, {0, 0}},

C[ -U[3] , U[3] , V[1] ] == {{I*gc437, 0}, {I*gc437, 0}, {0, 0}},

C[ -U[3] , U[3] , V[2] ] == {{I*gc438, 0}, {I*gc438, 0}, {0, 0}},

C[ S[7] , -U[3] , U[2] ] == {{-(EL^2*(cw - sw)*(cw + sw)*vev)/(4*cw*sw^2), 0}},

C[ -U[3] , U[2] , V[3] ] == {{I*gc440, 0}, {I*gc440, 0}, {0, 0}},

C[ S[7] , -U[2] , U[4] ] == {{(EL^2*(cw^2 + sw^2)*vev)/(4*cw*sw^2), 0}},

C[ -U[2] , U[4] , V[3] ] == {{I*gc442, 0}, {I*gc442, 0}, {0, 0}},

C[ -S[7] , -U[2] , U[3] ] == {{-(EL^2*(cw^2 + sw^2)*vev)/(4*cw*sw^2), 0}},

C[ -U[2] , U[3] , -V[3] ] == {{I*gc444, 0}, {I*gc444, 0}, {0, 0}},

C[ -U[5, {e1x1}] , U[5, {e2x1}] , V[4, {e3x2}] ] == {{gc445*SUNF[e3x2, e1x1, e2x1], 0}, {gc445*SUNF[e3x2, e1x1, e2x1], 0}, {0, 0}}

}

(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)

(* Parameter replacement lists (These lists were created by FeynRules) *)

(* FA Couplings *)

M$FACouplings = {
     gc1 -> -GS,
     gc2 -> -GS^2,
     gc3 -> EL,
     gc4 -> -EL^2,
     gc5 -> (cw*EL)/sw,
     gc6 -> EL^2/sw^2,
     gc7 -> (cw*EL^2)/sw,
     gc8 -> -((cw^2*EL^2)/sw^2),
     gc171 -> -EL,
     gc172 -> -(EL*(cphi^2 + sphi^2)),
     gc173 -> -(EL*(cphi^2 + sphi^2)),
     gc184 -> EL/(2*sw),
     gc185 -> (cab*EL)/(2*sw),
     gc186 -> -(EL*sab)/(2*sw),
     gc187 -> (cphi*EL)/(2*sw),
     gc188 -> (EL*sphi)/(2*sw),
     gc189 -> -(cab*cphi*EL)/(2*sw),
     gc190 -> -(cab*EL*sphi)/(2*sw),
     gc191 -> -(cphi*EL*sab)/(2*sw),
     gc192 -> -(EL*sab*sphi)/(2*sw),
     gc203 -> EL/(2*sw),
     gc204 -> -(cab*EL)/(2*sw),
     gc205 -> (EL*sab)/(2*sw),
     gc206 -> (cphi*EL)/(2*sw),
     gc207 -> (EL*sphi)/(2*sw),
     gc208 -> (cab*cphi*EL)/(2*sw),
     gc209 -> (cab*EL*sphi)/(2*sw),
     gc210 -> (cphi*EL*sab)/(2*sw),
     gc211 -> (EL*sab*sphi)/(2*sw),
     gc228 -> -(cab*EL*(cw^2 + sw^2))/(2*cw*sw),
     gc229 -> (EL*sab*(cw^2 + sw^2))/(2*cw*sw),
     gc230 -> -(cw*EL)/(2*sw) + (EL*sw)/(2*cw),
     gc231 -> -(cab*EL*(cw^2 + sw^2))/(2*cw*sw),
     gc232 -> -(EL*sab*(cw^2 + sw^2))/(2*cw*sw),
     gc233 -> -(cphi*EL*sphi*(cw^2 + sw^2))/(2*cw*sw),
     gc234 -> EL/(2*cw*sw),
     gc235 -> (cphi*EL*sphi*(cw^2 + sw^2))/(2*cw*sw),
     gc236 -> (EL*(2*sphi^2*sw^2 + cphi^2*(-cw^2 + sw^2)))/(2*cw*sw),
     gc268 -> -EL,
     gc269 -> -EL,
     gc270 -> -EL,
     gc271 -> (2*EL)/3,
     gc272 -> (2*EL)/3,
     gc273 -> (2*EL)/3,
     gc274 -> -EL/3,
     gc275 -> -EL/3,
     gc276 -> -EL/3,
     gc277 -> GS,
     gc278 -> GS,
     gc279 -> GS,
     gc280 -> GS,
     gc281 -> GS,
     gc282 -> GS,
     gc283 -> (CKM2x3*EL)/(Sqrt[2]*sw),
     gc284 -> (CKM2x1*EL)/(Sqrt[2]*sw),
     gc285 -> (CKM2x2*EL)/(Sqrt[2]*sw),
     gc286 -> (CKM3x3*EL)/(Sqrt[2]*sw),
     gc287 -> (CKM3x1*EL)/(Sqrt[2]*sw),
     gc288 -> (CKM3x2*EL)/(Sqrt[2]*sw),
     gc289 -> (CKM1x3*EL)/(Sqrt[2]*sw),
     gc290 -> (CKM1x1*EL)/(Sqrt[2]*sw),
     gc291 -> (CKM1x2*EL)/(Sqrt[2]*sw),
     gc292 -> (EL*Conjugate[CKM2x3])/(Sqrt[2]*sw),
     gc293 -> (EL*Conjugate[CKM3x3])/(Sqrt[2]*sw),
     gc294 -> (EL*Conjugate[CKM1x3])/(Sqrt[2]*sw),
     gc295 -> (EL*Conjugate[CKM2x1])/(Sqrt[2]*sw),
     gc296 -> (EL*Conjugate[CKM3x1])/(Sqrt[2]*sw),
     gc297 -> (EL*Conjugate[CKM1x1])/(Sqrt[2]*sw),
     gc298 -> (EL*Conjugate[CKM2x2])/(Sqrt[2]*sw),
     gc299 -> (EL*Conjugate[CKM3x2])/(Sqrt[2]*sw),
     gc300 -> (EL*Conjugate[CKM1x2])/(Sqrt[2]*sw),
     gc301 -> EL/(Sqrt[2]*sw),
     gc302 -> EL/(Sqrt[2]*sw),
     gc303 -> EL/(Sqrt[2]*sw),
     gc304 -> EL/(Sqrt[2]*sw),
     gc305 -> EL/(Sqrt[2]*sw),
     gc306 -> EL/(Sqrt[2]*sw),
     gc307L -> (cw*EL)/(2*sw) - (EL*sw)/(6*cw),
     gc307R -> (-2*EL*sw)/(3*cw),
     gc308L -> (cw*EL)/(2*sw) - (EL*sw)/(6*cw),
     gc308R -> (-2*EL*sw)/(3*cw),
     gc309L -> (cw*EL)/(2*sw) - (EL*sw)/(6*cw),
     gc309R -> (-2*EL*sw)/(3*cw),
     gc310L -> -(EL*(3*cw^2 + sw^2))/(6*cw*sw),
     gc310R -> (EL*sw)/(3*cw),
     gc311L -> -(EL*(3*cw^2 + sw^2))/(6*cw*sw),
     gc311R -> (EL*sw)/(3*cw),
     gc312L -> -(EL*(3*cw^2 + sw^2))/(6*cw*sw),
     gc312R -> (EL*sw)/(3*cw),
     gc313 -> (EL*(cw^2 + sw^2))/(2*cw*sw),
     gc314 -> (EL*(cw^2 + sw^2))/(2*cw*sw),
     gc315 -> (EL*(cw^2 + sw^2))/(2*cw*sw),
     gc316L -> -(EL*(cw^2 - sw^2))/(2*cw*sw),
     gc316R -> (EL*sw)/cw,
     gc317L -> -(EL*(cw^2 - sw^2))/(2*cw*sw),
     gc317R -> (EL*sw)/cw,
     gc318L -> -(EL*(cw^2 - sw^2))/(2*cw*sw),
     gc318R -> (EL*sw)/cw,
     gc319L -> -(yb*Conjugate[CKM2x3]),
     gc319R -> yc*Conjugate[CKM2x3],
     gc320L -> -(yb*Conjugate[CKM3x3]),
     gc320R -> yt*Conjugate[CKM3x3],
     gc321L -> -(yb*Conjugate[CKM1x3]),
     gc321R -> yup*Conjugate[CKM1x3],
     gc322L -> -(ydo*Conjugate[CKM2x1]),
     gc322R -> yc*Conjugate[CKM2x1],
     gc323L -> -(ydo*Conjugate[CKM3x1]),
     gc323R -> yt*Conjugate[CKM3x1],
     gc324L -> -(ydo*Conjugate[CKM1x1]),
     gc324R -> yup*Conjugate[CKM1x1],
     gc325L -> -(ys*Conjugate[CKM2x2]),
     gc325R -> yc*Conjugate[CKM2x2],
     gc326L -> -(ys*Conjugate[CKM3x2]),
     gc326R -> yt*Conjugate[CKM3x2],
     gc327L -> -(ys*Conjugate[CKM1x2]),
     gc327R -> yup*Conjugate[CKM1x2],
     gc328L -> -(yb/Sqrt[2]),
     gc328R -> yb/Sqrt[2],
     gc329L -> -(ydo/Sqrt[2]),
     gc329R -> ydo/Sqrt[2],
     gc330L -> -(ys/Sqrt[2]),
     gc330R -> ys/Sqrt[2],
     gc331 -> -((cab*yb)/Sqrt[2]),
     gc332 -> -((cab*ydo)/Sqrt[2]),
     gc333 -> -((cab*ys)/Sqrt[2]),
     gc334 -> (sab*yb)/Sqrt[2],
     gc335 -> (sab*ydo)/Sqrt[2],
     gc336 -> (sab*ys)/Sqrt[2],
     gc337 -> -ye,
     gc338 -> -ym,
     gc339 -> -ytau,
     gc340L -> -(ye/Sqrt[2]),
     gc340R -> ye/Sqrt[2],
     gc341L -> -(ym/Sqrt[2]),
     gc341R -> ym/Sqrt[2],
     gc342L -> -(ytau/Sqrt[2]),
     gc342R -> ytau/Sqrt[2],
     gc343 -> (-(cab*ye) - sab*yzee)/Sqrt[2],
     gc344 -> (-(cab*ym) - sab*yzmm)/Sqrt[2],
     gc345 -> (-(cab*ytau) - sab*yztt)/Sqrt[2],
     gc346 -> (sab*ye - cab*yzee)/Sqrt[2],
     gc347 -> (sab*ym - cab*yzmm)/Sqrt[2],
     gc348 -> (sab*ytau - cab*yztt)/Sqrt[2],
     gc349 -> -(cphi*yzee),
     gc350L -> -2*fem*sphi - cphi*yzme,
     gc350R -> -2*fem*sphi,
     gc351L -> -2*fet*sphi - cphi*yzte,
     gc351R -> -2*fet*sphi,
     gc352L -> 2*fem*sphi - cphi*yzem,
     gc352R -> 2*fem*sphi,
     gc353 -> -(cphi*yzmm),
     gc354L -> -2*fmt*sphi - cphi*yztm,
     gc354R -> -2*fmt*sphi,
     gc355L -> 2*fet*sphi - cphi*yzet,
     gc355R -> 2*fet*sphi,
     gc356L -> 2*fmt*sphi - cphi*yzmt,
     gc356R -> 2*fmt*sphi,
     gc357 -> -(cphi*yztt),
     gc358 -> -(sphi*yzee),
     gc359L -> 2*cphi*fem - sphi*yzme,
     gc359R -> 2*cphi*fem,
     gc360L -> 2*cphi*fet - sphi*yzte,
     gc360R -> 2*cphi*fet,
     gc361L -> -2*cphi*fem - sphi*yzem,
     gc361R -> -2*cphi*fem,
     gc362 -> -(sphi*yzmm),
     gc363L -> 2*cphi*fmt - sphi*yztm,
     gc363R -> 2*cphi*fmt,
     gc364L -> -2*cphi*fet - sphi*yzet,
     gc364R -> -2*cphi*fet,
     gc365L -> -2*cphi*fmt - sphi*yzmt,
     gc365R -> -2*cphi*fmt,
     gc366 -> -(sphi*yztt),
     gc367L -> -(yzee/Sqrt[2]),
     gc367R -> yzee/Sqrt[2],
     gc368L -> -(yzme/Sqrt[2]),
     gc368R -> yzem/Sqrt[2],
     gc369L -> -(yzte/Sqrt[2]),
     gc369R -> yzet/Sqrt[2],
     gc370L -> -(yzem/Sqrt[2]),
     gc370R -> yzme/Sqrt[2],
     gc371L -> -(yzmm/Sqrt[2]),
     gc371R -> yzmm/Sqrt[2],
     gc372L -> -(yztm/Sqrt[2]),
     gc372R -> yzmt/Sqrt[2],
     gc373L -> -(yzet/Sqrt[2]),
     gc373R -> yzte/Sqrt[2],
     gc374L -> -(yzmt/Sqrt[2]),
     gc374R -> yztm/Sqrt[2],
     gc375L -> -(yztt/Sqrt[2]),
     gc375R -> yztt/Sqrt[2],
     gc376L -> -((cab*yzme)/Sqrt[2]),
     gc376R -> -((cab*yzem)/Sqrt[2]),
     gc377L -> -((cab*yzte)/Sqrt[2]),
     gc377R -> -((cab*yzet)/Sqrt[2]),
     gc378L -> -((cab*yzem)/Sqrt[2]),
     gc378R -> -((cab*yzme)/Sqrt[2]),
     gc379L -> -((cab*yztm)/Sqrt[2]),
     gc379R -> -((cab*yzmt)/Sqrt[2]),
     gc380L -> -((cab*yzet)/Sqrt[2]),
     gc380R -> -((cab*yzte)/Sqrt[2]),
     gc381L -> -((cab*yzmt)/Sqrt[2]),
     gc381R -> -((cab*yztm)/Sqrt[2]),
     gc382L -> -((sab*yzme)/Sqrt[2]),
     gc382R -> -((sab*yzem)/Sqrt[2]),
     gc383L -> -((sab*yzte)/Sqrt[2]),
     gc383R -> -((sab*yzet)/Sqrt[2]),
     gc384L -> -((sab*yzem)/Sqrt[2]),
     gc384R -> -((sab*yzme)/Sqrt[2]),
     gc385L -> -((sab*yztm)/Sqrt[2]),
     gc385R -> -((sab*yzmt)/Sqrt[2]),
     gc386L -> -((sab*yzet)/Sqrt[2]),
     gc386R -> -((sab*yzte)/Sqrt[2]),
     gc387L -> -((sab*yzmt)/Sqrt[2]),
     gc387R -> -((sab*yztm)/Sqrt[2]),
     gc388L -> CKM2x3*yc,
     gc388R -> -(CKM2x3*yb),
     gc389L -> CKM2x1*yc,
     gc389R -> -(CKM2x1*ydo),
     gc390L -> CKM2x2*yc,
     gc390R -> -(CKM2x2*ys),
     gc391L -> CKM3x3*yt,
     gc391R -> -(CKM3x3*yb),
     gc392L -> CKM3x1*yt,
     gc392R -> -(CKM3x1*ydo),
     gc393L -> CKM3x2*yt,
     gc393R -> -(CKM3x2*ys),
     gc394L -> CKM1x3*yup,
     gc394R -> -(CKM1x3*yb),
     gc395L -> CKM1x1*yup,
     gc395R -> -(CKM1x1*ydo),
     gc396L -> CKM1x2*yup,
     gc396R -> -(CKM1x2*ys),
     gc397L -> yc/Sqrt[2],
     gc397R -> -(yc/Sqrt[2]),
     gc398L -> yt/Sqrt[2],
     gc398R -> -(yt/Sqrt[2]),
     gc399L -> yup/Sqrt[2],
     gc399R -> -(yup/Sqrt[2]),
     gc400 -> -((cab*yc)/Sqrt[2]),
     gc401 -> -((cab*yt)/Sqrt[2]),
     gc402 -> -((cab*yup)/Sqrt[2]),
     gc403 -> (sab*yc)/Sqrt[2],
     gc404 -> (sab*yt)/Sqrt[2],
     gc405 -> (sab*yup)/Sqrt[2],
     gc406L -> -2*cphi*fem,
     gc406R -> -2*cphi*fem - sphi*yzem,
     gc407L -> 2*fem*sphi,
     gc407R -> 2*fem*sphi - cphi*yzem,
     gc408L -> -2*cphi*fet,
     gc408R -> -2*cphi*fet - sphi*yzet,
     gc409L -> 2*fet*sphi,
     gc409R -> 2*fet*sphi - cphi*yzet,
     gc410L -> 2*cphi*fem,
     gc410R -> 2*cphi*fem - sphi*yzme,
     gc411L -> -2*fem*sphi,
     gc411R -> -2*fem*sphi - cphi*yzme,
     gc412L -> -2*cphi*fmt,
     gc412R -> -2*cphi*fmt - sphi*yzmt,
     gc413L -> 2*fmt*sphi,
     gc413R -> 2*fmt*sphi - cphi*yzmt,
     gc414L -> 2*cphi*fet,
     gc414R -> 2*cphi*fet - sphi*yzte,
     gc415L -> -2*fet*sphi,
     gc415R -> -2*fet*sphi - cphi*yzte,
     gc416L -> 2*cphi*fmt,
     gc416R -> 2*cphi*fmt - sphi*yztm,
     gc417L -> -2*fmt*sphi,
     gc417R -> -2*fmt*sphi - cphi*yztm,
     gc418R -> -ye,
     gc419R -> -ym,
     gc420R -> -ytau,
     gc421R -> -(cphi*yzee),
     gc422R -> -(sphi*yzee),
     gc423R -> -(cphi*yzmm),
     gc424R -> -(sphi*yzmm),
     gc425R -> -(cphi*yztt),
     gc426R -> -(sphi*yztt),
     gc427 -> EL,
     gc428 -> -EL,
     gc430 -> EL,
     gc431 -> -EL,
     gc432 -> -((cw*EL)/sw),
     gc434 -> (cw*EL)/sw,
     gc436 -> -EL,
     gc437 -> EL,
     gc438 -> (cw*EL)/sw,
     gc440 -> -((cw*EL)/sw),
     gc442 -> (cw*EL)/sw,
     gc444 -> -((cw*EL)/sw),
     gc445 -> GS};

